---
title: "p8105_hw5_rd3096"
author: Timothy Du
output: github_document
---

# load necessary pakages 
```{r setup}
library(tidyverse)
library(rvest)
library(ggplot2)
library(purrr)

set.seed(1)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
## problem 1

we define a function to simulate birthdays and check for duplicates
```{r}
simulate_shared_birthday = function(n) {
  
  birthdays = sample(1:365, n, replace = TRUE)
  
  has_duplicate = any(duplicated(birthdays))
}

```
we run this 10000 timese based on a sample size of 2-50
```{r}
compute_duplicate_probability = function(n) {
  
  simulations = map(1:10000, ~simulate_shared_birthday(n)) %>% 
    unlist()
  
  prob = mean(simulations)
  
  # Return result as a tibble
  tibble(
    group_size = n,
    prob_duplicate = prob
  )
}

result_final = map_dfr(2:50, compute_duplicate_probability)

result_final
```

Make a plot showing the relationship between probability and group size
```{r}
ggplot(
  result_final, 
  aes(x = group_size, y = prob_duplicate)
  ) +
  geom_smooth() +
  geom_point(alpha=0.5) +
  labs(
    title = "Probability of Shared Birthday as a Function of Group Size",
    x = "Group Size",
    y = "Probability of Shared Birthday"
  ) +
  theme_minimal()
```

## problem 2

create one-sample t test function and power function

```{r}
simulation_test = function(mu, n=30,sigma=5) {
  
  x = rnorm(n=30, mean=mu, sd = sigma)

  one_sample_ttest = t.test (x,mu = 0) %>% 
    broom::tidy()
  
    tibble(
      mu_hat = one_sample_ttest$estimate,
      p_value = one_sample_ttest$p.value
    )
}

power_and_avemu = function(mu, n = 30, sigma = 5) {
 
  simulation_test_results = map_dfr(1:5000, ~ simulation_test(mu, n = 30,sigma = 5))
  
  power = mean(simulation_test_results$p_value < 0.05, na.rm = TRUE)
  
  avg_mu_hat = mean(simulation_test_results$mu_hat, na.rm = TRUE)
  
  # Return a tibble with the true mu and calculated power
  tibble(
    true_mu = mu,
    power = power,
    avg_mu=avg_mu_hat
  )
}

mu_values = c(1, 2, 3, 4, 5, 6)

# Calculate power for each value of mu
power_results = map_dfr(mu_values, power_and_avemu)

power_results

ggplot(
  power_results, aes(x = true_mu, y = power,color=true_mu)) +
  geom_line() +
  scale_color_viridis_c()+
  geom_point(alpha=0.8) +
  labs(
    title = "Power of One-Sample t-Test as a Function of Effect Size",
    x = "True Mean (Effect Size)",
    y = "Power"
  ) +
  theme_minimal()
```

Complete the two plots analyzing average estimate of mu_hat and true mu
```{r}
estimate_results = map_dfr(mu_values, power_and_avemu)

estimate_results 

ggplot(estimate_results, aes(x = true_mu, y = avg_mu, color=true_mu)) +
  geom_line() + 
  scale_color_viridis_c()+
  geom_point(size = 2) +     
  labs(
    title = "Average Estimate of μ̂ as a Function of True μ",
    x = "True Mean (μ)",
    y = "Average Estimate of μ̂"
  ) +
  theme_minimal()
```

